### ISSUE TITLE
std/tokio simple: timeout not working, it is actually None on Drop

### ISSUE THREAD

**Issue by beckend** [t3hmrman/async-dropper#12]
https://github.com/t3hmrman/async-dropper/blob/main/crates/async-dropper-simple/src/lib.rs#L65

This line will replace self with Default impl and `timeout` becomes None: https://github.com/t3hmrman/async-dropper/blob/main/crates/async-dropper-simple/src/lib.rs#L61

Also as a note, adding Deref and Derefmut would be desirable to get the inner otherwise this Struct is less useful.

**Comment by beckend** [comment]
You can also remove the `Default` requirement easily by setting `inner: Option<T>` and manually set the inner to `None` when implementing Default for the Struct.

**Comment by t3hmrman** [comment]
Hey @beckend thank you so much for pointing this out -- would you be willing to put the changes into a PR?

I think the tests wouldn't even have to change -- just the code would be fine!

**Comment by beckend** [comment]
Sent the PR. Consider the breaking nature.

**Comment by t3hmrman** [comment]
Thanks to the work in the PR and comments, these improvements have all landed in version 0.2.6:

https://github.com/t3hmrman/async-dropper/releases/tag/async-dropper-simple-v0.2.6

Thanks!
