### ISSUE TITLE
incorrect project name in README

### ISSUE THREAD

**Issue by simonwuelker** [t3hmrman/async-dropper#3]
> To get started working on developing situwatiion [...]

I guess you copy-pasted the README and forgot to change the project name ^^
[situwaition](https://github.com/t3hmrman/situwaition) also seems to be spelled wrong btw.

**Comment by t3hmrman** [comment]
Hey thanks for pointing this out! I definitely copy-pasted and missed this -- #1 has actually *already* addressed this though so hopefully I can merge that within the next like... 3 minutes.
