### ISSUE TITLE
AsyncDropError is not used

### ISSUE THREAD

**Issue by lok52** [t3hmrman/async-dropper#7]
`AsyncDropError` is not used in `async-dropper-derive`. Probably, the implementation should check for the error even if waiting on timeout was successful:
https://github.com/t3hmrman/async-dropper/blob/8d36da3a375adb9632dd9a7d5bc8f7c0e10a2e3b/crates/async-dropper-derive/src/lib.rs#L194-L197

**Comment by t3hmrman** [comment]
Hey @lok52 thanks for the spot! Your comment made me realize I needed to back and clean lints so I've done a bunch of that, and will probably do some more maintenance like updating deps.

Regarding the issue at hand, I think you're right about the implementation checking for the error, would you like to take a shot at putting up a PR?

[EDIT] New releases out for all the packages after lint fixes and dep updates -- once this is resolved (however we handle it) I'll make another quick patch release!

**Comment by lok52** [comment]
> I think you're right about the implementation checking for the error, would you like to take a shot at putting up a PR?

Yeah, definitely. Will prepare a PR in a couple of days.

**Comment by t3hmrman** [comment]
Hey just a heads up, v0.3.0 just went live so there are a few changes in the codebase in case you have pulled it already:

https://crates.io/crates/async-dropper
https://github.com/t3hmrman/async-dropper/releases/tag/async-dropper-v0.3.0


This bug should still be there, so please feel free to fix it!

**Comment by lok52** [comment]
Hey! Just prepared a PR and modified derive examples for showcase and testing reasons

**Comment by t3hmrman** [comment]
Thanks @lok52 a bit late but finally got your review done, apologies for the delay! :bow:
