### ISSUE TITLE
Duration not found

### ISSUE THREAD

**Issue by horacimacias** [t3hmrman/async-dropper#8]
Looks like the derive is using Duration without the full name so code does not compile unless you `use std::time::Duration;`
Given this is hidden inside the derive, it would be better if this was already done by the derive and the user does not need to `use std::time::Duration;`

**Comment by t3hmrman** [comment]
Hey @horacimacias thanks for the report -- this is definitely a problem and I have a PR up for this already, a new patch release should be out soon.

**Comment by t3hmrman** [comment]
Hey @horacimacias just an update, there should be a new version available that fixes this bug:

[`async-dropper` v0.2.5](https://crates.io/crates/async-dropper/0.2.5)

[Github release](https://github.com/t3hmrman/async-dropper/releases/tag/async-dropper-derive-v0.2.6)

**Comment by horacimacias** [comment]
ah, thanks! that explains why suddenly on the PR I was preparing things are working fine without the use statement :)
I thought I was going (more) crazy.

**Comment by t3hmrman** [comment]
~~Oh no! I'm sorry I should have waited for you to respond!~~

~~Thank you for taking the time to start up a PR, I would have let you finish it if I had known. Again I appreciate the report and I will certainly get out of the way so you can fix the bug next time :)~~

[EDIT] Looks like I misunderstood what you meant (the PR you were working on was *your* PR, I assume!). Glad I was able to fix the problem out from under you :)

**Comment by horacimacias** [comment]
no worries, thank you!
